import json
from pathlib import Path
from sqlmodel import SQLModel, Session
import asyncio
import aiofiles
from .movie_utils import process_movie_data
from app.models import (
    Movie as DBMovie,
    RealPerson,
    Genre,
    Platform,
    CastLink,
    PydanticMovie,
    Director,
    Review,
    Follow,
)
from app.db.utils import engine, AsyncSessionLocal



ROOT_DIR = Path(__file__).resolve().parent.parent.parent
JSON_FILE_PATH = ROOT_DIR / "peliculas.json"



async def seed_initial_data():
    """
    Carga los datos iniciales (seeding) desde un JSON de forma asíncrona.
    """
    print(f"Buscando archivo de datos en: {JSON_FILE_PATH}")
    if not JSON_FILE_PATH.exists():
        print(f"Error: El archivo {JSON_FILE_PATH} no fue encontrado.")
        return

    print(f"Leyendo datos desde {JSON_FILE_PATH} (async)...")
    # NUEVO: Lectura de archivo asíncrona con aiofiles
    try:
        async with aiofiles.open(JSON_FILE_PATH, "r", encoding="utf-8") as file:
            content = await file.read()
            movies_list = json.loads(content)
    except Exception as e:
        print(f"Error al leer o parsear el JSON: {e}")
        return

    # NUEVO: Usamos AsyncSessionLocal() directamente para controlar la transacción
    async with AsyncSessionLocal() as session:
        try:
            # Verificar si el seeding ya se realizó
            first_movie_id = movies_list[0].get("id")
            if not first_movie_id:
                print("Error: El JSON no parece tener películas válidas con 'id'.")
                return

            # NUEVO: 'await session.get'
            existing_movie = await session.get(DBMovie, first_movie_id)
            if existing_movie:
                print("La base de datos ya parece estar poblada. Proceso de seeding omitido.")
                return

            # --- Procesamiento en Paralelo ---
            print("\nIniciando carga de películas (en paralelo)...")
            tasks = []
            for movie_data in movies_list:
                # NUEVO: Creamos una tarea por cada película
                tasks.append(process_movie_data(session, movie_data))

            # NUEVO: Ejecutamos todas las tareas concurrentemente
            await asyncio.gather(*tasks)

            # --- Commit de Películas ---
            print("\nGuardando películas en la base de datos...")
            # NUEVO: 'await session.commit'
            await session.commit()
            print("Películas guardadas exitosamente.")

            # --- Agregar Mock Ratings ---
            print("Agregando ratings mock...")

            # Agregar los ratings mock
            mock_ratings = [
                # Ratings existentes (manteniendo compatibilidad)
                {"user_id": 1, "movie_id": 1, "rating": 5.0},
                {"user_id": 1, "movie_id": 3, "rating": 3.0},
                {"user_id": 1, "movie_id": 4, "rating": 4.0},
                {"user_id": 1, "movie_id": 5, "rating": 5.0},
                {"user_id": 2, "movie_id": 1, "rating": 4.0},
                {"user_id": 2, "movie_id": 6, "rating": 4.5},
                {"user_id": 2, "movie_id": 7, "rating": 3.5},
                {"user_id": 2, "movie_id": 8, "rating": 4.0},
                {"user_id": 3, "movie_id": 3, "rating": 4.0},
                {"user_id": 3, "movie_id": 4, "rating": 5.0},
                {"user_id": 3, "movie_id": 9, "rating": 4.5},
                {"user_id": 3, "movie_id": 10, "rating": 3.0},
                {"user_id": 3, "movie_id": 11, "rating": 4.0},
                {"user_id": 4, "movie_id": 5, "rating": 4.5},
                {"user_id": 4, "movie_id": 6, "rating": 5.0},
                {"user_id": 4, "movie_id": 14, "rating": 4.5},
                {"user_id": 5, "movie_id": 1, "rating": 4.0},
                {"user_id": 5, "movie_id": 7, "rating": 4.5},
                {"user_id": 5, "movie_id": 8, "rating": 5.0},
                {"user_id": 5, "movie_id": 9, "rating": 3.5},
                {"user_id": 5, "movie_id": 10, "rating": 4.0},
                {"user_id": 6, "movie_id": 11, "rating": 5.0},
                {"user_id": 6, "movie_id": 14, "rating": 4.5},
                {"user_id": 1, "movie_id": 6, "rating": 4.0},
                {"user_id": 2, "movie_id": 9, "rating": 4.5},
                {"user_id": 4, "movie_id": 1, "rating": 4.5},
                {"user_id": 5, "movie_id": 3, "rating": 3.5},
                {"user_id": 6, "movie_id": 5, "rating": 4.0},
                {"user_id": 7, "movie_id": 1, "rating": 2.0},
                {"user_id": 7, "movie_id": 7, "rating": 4.0},
                {"user_id": 7, "movie_id": 10, "rating": 1.5},
                {"user_id": 7, "movie_id": 14, "rating": 3.0},
                {"user_id": 8, "movie_id": 3, "rating": 5.0},
                {"user_id": 8, "movie_id": 4, "rating": 4.5},
                {"user_id": 8, "movie_id": 9, "rating": 5.0},
                {"user_id": 8, "movie_id": 11, "rating": 4.0},
                {"user_id": 9, "movie_id": 5, "rating": 2.5},
                {"user_id": 9, "movie_id": 6, "rating": 3.0},
                {"user_id": 9, "movie_id": 8, "rating": 2.0},
                {"user_id": 9, "movie_id": 14, "rating": 4.0},
                {"user_id": 9, "movie_id": 1, "rating": 3.5},
                {"user_id": 10, "movie_id": 7, "rating": 3.0},
                {"user_id": 10, "movie_id": 9, "rating": 5.0},
                {"user_id": 10, "movie_id": 10, "rating": 2.5},
                {"user_id": 1, "movie_id": 9, "rating": 4.5},
                {"user_id": 3, "movie_id": 5, "rating": 4.0},
                {"user_id": 4, "movie_id": 8, "rating": 4.5},
                {"user_id": 5, "movie_id": 11, "rating": 3.0},
                {"user_id": 6, "movie_id": 7, "rating": 4.5},
                {"user_id": 7, "movie_id": 4, "rating": 2.5},
                {"user_id": 8, "movie_id": 6, "rating": 4.0},
                {"user_id": 10, "movie_id": 1, "rating": 5.0},
                {"user_id": 11, "movie_id": 15, "rating": 4.5},
                {"user_id": 11, "movie_id": 16, "rating": 5.0},
                {"user_id": 11, "movie_id": 17, "rating": 3.5},
                {"user_id": 11, "movie_id": 18, "rating": 4.0},
                {"user_id": 11, "movie_id": 19, "rating": 2.0},
                {"user_id": 12, "movie_id": 1, "rating": 2.5},
                {"user_id": 12, "movie_id": 5, "rating": 3.0},
                {"user_id": 12, "movie_id": 10, "rating": 2.0},
                {"user_id": 12, "movie_id": 15, "rating": 1.5},
                {"user_id": 12, "movie_id": 20, "rating": 3.5},
                {"user_id": 13, "movie_id": 6, "rating": 5.0},
                {"user_id": 13, "movie_id": 8, "rating": 4.5},
                {"user_id": 13, "movie_id": 16, "rating": 4.0},
                {"user_id": 13, "movie_id": 18, "rating": 4.5},
                {"user_id": 14, "movie_id": 7, "rating": 5.0},
                {"user_id": 14, "movie_id": 9, "rating": 3.0},
                {"user_id": 14, "movie_id": 14, "rating": 4.5},
                {"user_id": 14, "movie_id": 17, "rating": 2.5},
                {"user_id": 15, "movie_id": 1, "rating": 5.0},
                {"user_id": 15, "movie_id": 3, "rating": 4.5},
                {"user_id": 15, "movie_id": 4, "rating": 5.0},
                {"user_id": 15, "movie_id": 11, "rating": 4.0},
                {"user_id": 11, "movie_id": 3, "rating": 4.0},
                {"user_id": 12, "movie_id": 7, "rating": 2.5},
                {"user_id": 13, "movie_id": 9, "rating": 4.5},
                {"user_id": 14, "movie_id": 11, "rating": 3.5},
                {"user_id": 15, "movie_id": 6, "rating": 4.0},
                {"user_id": 1, "movie_id": 15, "rating": 4.5},
                {"user_id": 2, "movie_id": 16, "rating": 3.0},
                {"user_id": 3, "movie_id": 17, "rating": 4.0},
                {"user_id": 4, "movie_id": 18, "rating": 2.5},
                {"user_id": 5, "movie_id": 19, "rating": 4.5},
                {"user_id": 6, "movie_id": 20, "rating": 3.5},
                {"user_id": 7, "movie_id": 15, "rating": 2.0},
                {"user_id": 8, "movie_id": 16, "rating": 4.5},
                {"user_id": 9, "movie_id": 17, "rating": 3.0},
                {"user_id": 10, "movie_id": 18, "rating": 4.0},
                # Nuevos ratings mock variados y extensos
                {"user_id": 1, "movie_id": 21, "rating": 4.0},
                {"user_id": 1, "movie_id": 22, "rating": 3.5},
                {"user_id": 1, "movie_id": 23, "rating": 5.0},
                {"user_id": 1, "movie_id": 24, "rating": 2.5},
                {"user_id": 1, "movie_id": 25, "rating": 4.5},
                {"user_id": 1, "movie_id": 26, "rating": 3.0},
                {"user_id": 1, "movie_id": 27, "rating": 4.0},
                {"user_id": 1, "movie_id": 28, "rating": 5.0},
                {"user_id": 1, "movie_id": 30, "rating": 4.5},
                {"user_id": 2, "movie_id": 21, "rating": 3.5},
                {"user_id": 2, "movie_id": 22, "rating": 4.0},
                {"user_id": 2, "movie_id": 23, "rating": 4.5},
                {"user_id": 2, "movie_id": 24, "rating": 3.0},
                {"user_id": 2, "movie_id": 25, "rating": 5.0},
                {"user_id": 2, "movie_id": 26, "rating": 2.5},
                {"user_id": 2, "movie_id": 27, "rating": 4.0},
                {"user_id": 2, "movie_id": 28, "rating": 3.5},
                {"user_id": 2, "movie_id": 30, "rating": 1.5},
                {"user_id": 3, "movie_id": 21, "rating": 4.5},
                {"user_id": 3, "movie_id": 22, "rating": 3.0},
                {"user_id": 3, "movie_id": 23, "rating": 5.0},
                {"user_id": 3, "movie_id": 24, "rating": 4.0},
                {"user_id": 3, "movie_id": 25, "rating": 2.5},
                {"user_id": 3, "movie_id": 26, "rating": 4.5},
                {"user_id": 3, "movie_id": 27, "rating": 3.5},
                {"user_id": 3, "movie_id": 28, "rating": 4.0},
                {"user_id": 3, "movie_id": 30, "rating": 2.0},
                {"user_id": 4, "movie_id": 21, "rating": 3.0},
                {"user_id": 4, "movie_id": 22, "rating": 4.5},
                {"user_id": 4, "movie_id": 23, "rating": 4.0},
                {"user_id": 4, "movie_id": 24, "rating": 5.0},
                {"user_id": 4, "movie_id": 25, "rating": 3.5},
                {"user_id": 4, "movie_id": 26, "rating": 2.0},
                {"user_id": 4, "movie_id": 27, "rating": 4.5},
                {"user_id": 4, "movie_id": 28, "rating": 3.0},
                {"user_id": 4, "movie_id": 30, "rating": 5.0},
                {"user_id": 5, "movie_id": 21, "rating": 4.0},
                {"user_id": 5, "movie_id": 22, "rating": 5.0},
                {"user_id": 5, "movie_id": 23, "rating": 3.5},
                {"user_id": 5, "movie_id": 24, "rating": 2.5},
                {"user_id": 5, "movie_id": 25, "rating": 4.5},
                {"user_id": 5, "movie_id": 26, "rating": 4.0},
                {"user_id": 5, "movie_id": 27, "rating": 3.0},
                {"user_id": 5, "movie_id": 28, "rating": 4.5},
                {"user_id": 5, "movie_id": 30, "rating": 2.0},
                {"user_id": 6, "movie_id": 21, "rating": 2.5},
                {"user_id": 6, "movie_id": 22, "rating": 4.0},
                {"user_id": 6, "movie_id": 23, "rating": 4.5},
                {"user_id": 6, "movie_id": 24, "rating": 3.5},
                {"user_id": 6, "movie_id": 25, "rating": 5.0},
                {"user_id": 6, "movie_id": 26, "rating": 3.0},
                {"user_id": 6, "movie_id": 27, "rating": 4.0},
                {"user_id": 6, "movie_id": 28, "rating": 2.5},
                {"user_id": 6, "movie_id": 30, "rating": 3.5},
                {"user_id": 7, "movie_id": 21, "rating": 4.5},
                {"user_id": 7, "movie_id": 22, "rating": 3.0},
                {"user_id": 7, "movie_id": 23, "rating": 5.0},
                {"user_id": 7, "movie_id": 24, "rating": 4.0},
                {"user_id": 7, "movie_id": 25, "rating": 2.0},
                {"user_id": 7, "movie_id": 26, "rating": 4.5},
                {"user_id": 7, "movie_id": 27, "rating": 3.5},
                {"user_id": 7, "movie_id": 28, "rating": 4.0},
                {"user_id": 7, "movie_id": 30, "rating": 5.0},
                {"user_id": 8, "movie_id": 21, "rating": 3.5},
                {"user_id": 8, "movie_id": 22, "rating": 4.0},
                {"user_id": 8, "movie_id": 23, "rating": 4.5},
                {"user_id": 8, "movie_id": 24, "rating": 2.5},
                {"user_id": 8, "movie_id": 25, "rating": 3.0},
                {"user_id": 8, "movie_id": 26, "rating": 4.5},
                {"user_id": 8, "movie_id": 27, "rating": 5.0},
                {"user_id": 8, "movie_id": 28, "rating": 3.5},
                {"user_id": 8, "movie_id": 30, "rating": 2.0},
                {"user_id": 9, "movie_id": 21, "rating": 4.0},
                {"user_id": 9, "movie_id": 22, "rating": 5.0},
                {"user_id": 9, "movie_id": 23, "rating": 3.0},
                {"user_id": 9, "movie_id": 24, "rating": 4.5},
                {"user_id": 9, "movie_id": 25, "rating": 2.5},
                {"user_id": 9, "movie_id": 26, "rating": 4.0},
                {"user_id": 9, "movie_id": 27, "rating": 3.5},
                {"user_id": 9, "movie_id": 28, "rating": 4.5},
                {"user_id": 9, "movie_id": 30, "rating": 1.0},
                {"user_id": 10, "movie_id": 21, "rating": 2.0},
                {"user_id": 10, "movie_id": 22, "rating": 4.5},
                {"user_id": 10, "movie_id": 23, "rating": 4.0},
                {"user_id": 10, "movie_id": 24, "rating": 3.5},
                {"user_id": 10, "movie_id": 25, "rating": 5.0},
                {"user_id": 10, "movie_id": 26, "rating": 3.0},
                {"user_id": 10, "movie_id": 27, "rating": 4.0},
                {"user_id": 10, "movie_id": 28, "rating": 2.5},
                {"user_id": 10, "movie_id": 30, "rating": 3.5},
                {"user_id": 11, "movie_id": 21, "rating": 4.5},
                {"user_id": 11, "movie_id": 22, "rating": 3.5},
                {"user_id": 11, "movie_id": 23, "rating": 4.0},
                {"user_id": 11, "movie_id": 24, "rating": 5.0},
                {"user_id": 11, "movie_id": 25, "rating": 2.5},
                {"user_id": 11, "movie_id": 26, "rating": 4.0},
                {"user_id": 11, "movie_id": 27, "rating": 3.0},
                {"user_id": 11, "movie_id": 28, "rating": 4.5},
                {"user_id": 11, "movie_id": 30, "rating": 2.0},
                {"user_id": 12, "movie_id": 21, "rating": 3.0},
                {"user_id": 12, "movie_id": 22, "rating": 4.0},
                {"user_id": 12, "movie_id": 23, "rating": 4.5},
                {"user_id": 12, "movie_id": 24, "rating": 2.0},
                {"user_id": 12, "movie_id": 25, "rating": 3.5},
                {"user_id": 12, "movie_id": 26, "rating": 4.5},
                {"user_id": 12, "movie_id": 27, "rating": 5.0},
                {"user_id": 12, "movie_id": 28, "rating": 3.0},
                {"user_id": 12, "movie_id": 30, "rating": 2.5},
                {"user_id": 13, "movie_id": 21, "rating": 4.0},
                {"user_id": 13, "movie_id": 22, "rating": 5.0},
                {"user_id": 13, "movie_id": 23, "rating": 3.5},
                {"user_id": 13, "movie_id": 24, "rating": 4.5},
                {"user_id": 13, "movie_id": 25, "rating": 2.0},
                {"user_id": 13, "movie_id": 26, "rating": 4.0},
                {"user_id": 13, "movie_id": 27, "rating": 3.5},
                {"user_id": 13, "movie_id": 28, "rating": 4.5},
                {"user_id": 13, "movie_id": 30, "rating": 1.5},
                {"user_id": 14, "movie_id": 21, "rating": 2.5},
                {"user_id": 14, "movie_id": 22, "rating": 4.5},
                {"user_id": 14, "movie_id": 23, "rating": 4.0},
                {"user_id": 14, "movie_id": 24, "rating": 3.0},
                {"user_id": 14, "movie_id": 25, "rating": 5.0},
                {"user_id": 14, "movie_id": 26, "rating": 3.5},
                {"user_id": 14, "movie_id": 27, "rating": 4.0},
                {"user_id": 14, "movie_id": 28, "rating": 2.0},
                {"user_id": 14, "movie_id": 30, "rating": 3.0},
                {"user_id": 15, "movie_id": 21, "rating": 4.5},
                {"user_id": 15, "movie_id": 22, "rating": 3.0},
                {"user_id": 15, "movie_id": 23, "rating": 5.0},
                {"user_id": 15, "movie_id": 24, "rating": 4.0},
                {"user_id": 15, "movie_id": 25, "rating": 2.5},
                {"user_id": 15, "movie_id": 26, "rating": 4.5},
                {"user_id": 15, "movie_id": 27, "rating": 3.5},
                {"user_id": 15, "movie_id": 28, "rating": 4.0},
                {"user_id": 15, "movie_id": 30, "rating": 2.0},
                # Más películas (31-60)
                {"user_id": 1, "movie_id": 31, "rating": 4.0},
                {"user_id": 1, "movie_id": 32, "rating": 3.5},
                {"user_id": 1, "movie_id": 33, "rating": 5.0},
                {"user_id": 1, "movie_id": 34, "rating": 2.5},
                {"user_id": 1, "movie_id": 35, "rating": 4.5},
                {"user_id": 2, "movie_id": 31, "rating": 3.0},
                {"user_id": 2, "movie_id": 32, "rating": 4.0},
                {"user_id": 2, "movie_id": 33, "rating": 4.5},
                {"user_id": 2, "movie_id": 34, "rating": 2.0},
                {"user_id": 2, "movie_id": 35, "rating": 5.0},
                {"user_id": 3, "movie_id": 31, "rating": 4.5},
                {"user_id": 3, "movie_id": 32, "rating": 3.0},
                {"user_id": 3, "movie_id": 33, "rating": 5.0},
                {"user_id": 3, "movie_id": 34, "rating": 4.0},
                {"user_id": 3, "movie_id": 35, "rating": 2.5},
                {"user_id": 4, "movie_id": 31, "rating": 3.5},
                {"user_id": 4, "movie_id": 32, "rating": 4.5},
                {"user_id": 4, "movie_id": 33, "rating": 4.0},
                {"user_id": 4, "movie_id": 34, "rating": 5.0},
                {"user_id": 4, "movie_id": 35, "rating": 3.0},
                {"user_id": 5, "movie_id": 31, "rating": 4.0},
                {"user_id": 5, "movie_id": 32, "rating": 5.0},
                {"user_id": 5, "movie_id": 33, "rating": 3.5},
                {"user_id": 5, "movie_id": 34, "rating": 2.5},
                {"user_id": 5, "movie_id": 35, "rating": 4.5},
                {"user_id": 6, "movie_id": 31, "rating": 2.0},
                {"user_id": 6, "movie_id": 32, "rating": 4.0},
                {"user_id": 6, "movie_id": 33, "rating": 4.5},
                {"user_id": 6, "movie_id": 34, "rating": 3.5},
                {"user_id": 6, "movie_id": 35, "rating": 5.0},
                {"user_id": 7, "movie_id": 31, "rating": 4.5},
                {"user_id": 7, "movie_id": 32, "rating": 3.0},
                {"user_id": 7, "movie_id": 33, "rating": 5.0},
                {"user_id": 7, "movie_id": 34, "rating": 4.0},
                {"user_id": 7, "movie_id": 35, "rating": 2.0},
                {"user_id": 8, "movie_id": 31, "rating": 3.0},
                {"user_id": 8, "movie_id": 32, "rating": 4.5},
                {"user_id": 8, "movie_id": 33, "rating": 4.0},
                {"user_id": 8, "movie_id": 34, "rating": 2.5},
                {"user_id": 8, "movie_id": 35, "rating": 3.5},
                {"user_id": 9, "movie_id": 31, "rating": 4.0},
                {"user_id": 9, "movie_id": 32, "rating": 5.0},
                {"user_id": 9, "movie_id": 33, "rating": 3.0},
                {"user_id": 9, "movie_id": 34, "rating": 4.5},
                {"user_id": 9, "movie_id": 35, "rating": 2.5},
                {"user_id": 10, "movie_id": 31, "rating": 2.5},
                {"user_id": 10, "movie_id": 32, "rating": 4.0},
                {"user_id": 10, "movie_id": 33, "rating": 4.5},
                {"user_id": 10, "movie_id": 34, "rating": 3.0},
                {"user_id": 10, "movie_id": 35, "rating": 5.0},
                {"user_id": 11, "movie_id": 31, "rating": 4.5},
                {"user_id": 11, "movie_id": 32, "rating": 3.5},
                {"user_id": 11, "movie_id": 33, "rating": 4.0},
                {"user_id": 11, "movie_id": 34, "rating": 5.0},
                {"user_id": 11, "movie_id": 35, "rating": 2.0},
                {"user_id": 12, "movie_id": 31, "rating": 3.0},
                {"user_id": 12, "movie_id": 32, "rating": 4.0},
                {"user_id": 12, "movie_id": 33, "rating": 4.5},
                {"user_id": 12, "movie_id": 34, "rating": 2.5},
                {"user_id": 12, "movie_id": 35, "rating": 3.5},
                {"user_id": 13, "movie_id": 31, "rating": 4.0},
                {"user_id": 13, "movie_id": 32, "rating": 5.0},
                {"user_id": 13, "movie_id": 33, "rating": 3.5},
                {"user_id": 13, "movie_id": 34, "rating": 4.5},
                {"user_id": 13, "movie_id": 35, "rating": 2.0},
                {"user_id": 14, "movie_id": 31, "rating": 2.5},
                {"user_id": 14, "movie_id": 32, "rating": 4.5},
                {"user_id": 14, "movie_id": 33, "rating": 4.0},
                {"user_id": 14, "movie_id": 34, "rating": 3.0},
                {"user_id": 14, "movie_id": 35, "rating": 5.0},
                {"user_id": 15, "movie_id": 31, "rating": 4.5},
                {"user_id": 15, "movie_id": 32, "rating": 3.0},
                {"user_id": 15, "movie_id": 33, "rating": 5.0},
                {"user_id": 15, "movie_id": 34, "rating": 4.0},
                {"user_id": 15, "movie_id": 35, "rating": 2.5},
                # Películas 36-50 con variedad adicional
                {"user_id": 1, "movie_id": 36, "rating": 3.5},
                {"user_id": 1, "movie_id": 37, "rating": 4.0},
                {"user_id": 1, "movie_id": 38, "rating": 2.0},
                {"user_id": 1, "movie_id": 39, "rating": 4.5},
                {"user_id": 1, "movie_id": 40, "rating": 5.0},
                {"user_id": 2, "movie_id": 36, "rating": 4.0},
                {"user_id": 2, "movie_id": 37, "rating": 3.5},
                {"user_id": 2, "movie_id": 38, "rating": 4.5},
                {"user_id": 2, "movie_id": 39, "rating": 2.5},
                {"user_id": 2, "movie_id": 40, "rating": 3.0},
                {"user_id": 3, "movie_id": 36, "rating": 5.0},
                {"user_id": 3, "movie_id": 37, "rating": 4.0},
                {"user_id": 3, "movie_id": 38, "rating": 3.5},
                {"user_id": 3, "movie_id": 39, "rating": 4.5},
                {"user_id": 3, "movie_id": 40, "rating": 2.0},
                {"user_id": 4, "movie_id": 36, "rating": 2.5},
                {"user_id": 4, "movie_id": 37, "rating": 4.5},
                {"user_id": 4, "movie_id": 38, "rating": 4.0},
                {"user_id": 4, "movie_id": 39, "rating": 5.0},
                {"user_id": 4, "movie_id": 40, "rating": 3.5},
                {"user_id": 5, "movie_id": 36, "rating": 4.0},
                {"user_id": 5, "movie_id": 37, "rating": 5.0},
                {"user_id": 5, "movie_id": 38, "rating": 3.0},
                {"user_id": 5, "movie_id": 39, "rating": 2.5},
                {"user_id": 5, "movie_id": 40, "rating": 4.5},
                {"user_id": 6, "movie_id": 36, "rating": 3.5},
                {"user_id": 6, "movie_id": 37, "rating": 4.0},
                {"user_id": 6, "movie_id": 38, "rating": 5.0},
                {"user_id": 6, "movie_id": 39, "rating": 2.0},
                {"user_id": 6, "movie_id": 40, "rating": 4.5},
                {"user_id": 7, "movie_id": 36, "rating": 4.5},
                {"user_id": 7, "movie_id": 37, "rating": 3.0},
                {"user_id": 7, "movie_id": 38, "rating": 4.0},
                {"user_id": 7, "movie_id": 39, "rating": 5.0},
                {"user_id": 7, "movie_id": 40, "rating": 1.5},
                {"user_id": 8, "movie_id": 36, "rating": 2.0},
                {"user_id": 8, "movie_id": 37, "rating": 4.5},
                {"user_id": 8, "movie_id": 38, "rating": 4.0},
                {"user_id": 8, "movie_id": 39, "rating": 3.5},
                {"user_id": 8, "movie_id": 40, "rating": 5.0},
                {"user_id": 9, "movie_id": 36, "rating": 4.0},
                {"user_id": 9, "movie_id": 37, "rating": 5.0},
                {"user_id": 9, "movie_id": 38, "rating": 2.5},
                {"user_id": 9, "movie_id": 39, "rating": 4.5},
                {"user_id": 9, "movie_id": 40, "rating": 3.0},
                {"user_id": 10, "movie_id": 36, "rating": 3.5},
                {"user_id": 10, "movie_id": 37, "rating": 4.0},
                {"user_id": 10, "movie_id": 38, "rating": 4.5},
                {"user_id": 10, "movie_id": 39, "rating": 2.0},
                {"user_id": 10, "movie_id": 40, "rating": 5.0},
                {"user_id": 11, "movie_id": 36, "rating": 4.5},
                {"user_id": 11, "movie_id": 37, "rating": 3.5},
                {"user_id": 11, "movie_id": 38, "rating": 4.0},
                {"user_id": 11, "movie_id": 39, "rating": 5.0},
                {"user_id": 11, "movie_id": 40, "rating": 2.5},
                {"user_id": 12, "movie_id": 36, "rating": 2.0},
                {"user_id": 12, "movie_id": 37, "rating": 4.0},
                {"user_id": 12, "movie_id": 38, "rating": 4.5},
                {"user_id": 12, "movie_id": 39, "rating": 3.0},
                {"user_id": 12, "movie_id": 40, "rating": 5.0},
                {"user_id": 13, "movie_id": 36, "rating": 4.0},
                {"user_id": 13, "movie_id": 37, "rating": 5.0},
                {"user_id": 13, "movie_id": 38, "rating": 3.5},
                {"user_id": 13, "movie_id": 39, "rating": 4.5},
                {"user_id": 13, "movie_id": 40, "rating": 2.0},
                {"user_id": 14, "movie_id": 36, "rating": 3.0},
                {"user_id": 14, "movie_id": 37, "rating": 4.5},
                {"user_id": 14, "movie_id": 38, "rating": 4.0},
                {"user_id": 14, "movie_id": 39, "rating": 2.5},
                {"user_id": 14, "movie_id": 40, "rating": 5.0},
                {"user_id": 15, "movie_id": 36, "rating": 4.5},
                {"user_id": 15, "movie_id": 37, "rating": 3.0},
                {"user_id": 15, "movie_id": 38, "rating": 5.0},
                {"user_id": 15, "movie_id": 39, "rating": 4.0},
                {"user_id": 15, "movie_id": 40, "rating": 2.5},
                # Películas 41-50
                {"user_id": 1, "movie_id": 41, "rating": 4.0},
                {"user_id": 1, "movie_id": 42, "rating": 3.5},
                {"user_id": 1, "movie_id": 43, "rating": 5.0},
                {"user_id": 1, "movie_id": 44, "rating": 2.5},
                {"user_id": 1, "movie_id": 45, "rating": 4.5},
                {"user_id": 2, "movie_id": 41, "rating": 3.0},
                {"user_id": 2, "movie_id": 42, "rating": 4.0},
                {"user_id": 2, "movie_id": 43, "rating": 4.5},
                {"user_id": 2, "movie_id": 44, "rating": 2.0},
                {"user_id": 2, "movie_id": 45, "rating": 5.0},
                {"user_id": 3, "movie_id": 41, "rating": 4.5},
                {"user_id": 3, "movie_id": 42, "rating": 3.0},
                {"user_id": 3, "movie_id": 43, "rating": 5.0},
                {"user_id": 3, "movie_id": 44, "rating": 4.0},
                {"user_id": 3, "movie_id": 45, "rating": 2.5},
                {"user_id": 4, "movie_id": 41, "rating": 2.5},
                {"user_id": 4, "movie_id": 42, "rating": 4.5},
                {"user_id": 4, "movie_id": 43, "rating": 4.0},
                {"user_id": 4, "movie_id": 44, "rating": 5.0},
                {"user_id": 4, "movie_id": 45, "rating": 3.0},
                {"user_id": 5, "movie_id": 41, "rating": 4.0},
                {"user_id": 5, "movie_id": 42, "rating": 5.0},
                {"user_id": 5, "movie_id": 43, "rating": 3.5},
                {"user_id": 5, "movie_id": 44, "rating": 2.5},
                {"user_id": 5, "movie_id": 45, "rating": 4.5},
                {"user_id": 6, "movie_id": 41, "rating": 3.5},
                {"user_id": 6, "movie_id": 42, "rating": 4.0},
                {"user_id": 6, "movie_id": 43, "rating": 4.5},
                {"user_id": 6, "movie_id": 44, "rating": 2.0},
                {"user_id": 6, "movie_id": 45, "rating": 5.0},
                {"user_id": 7, "movie_id": 41, "rating": 4.5},
                {"user_id": 7, "movie_id": 42, "rating": 3.0},
                {"user_id": 7, "movie_id": 43, "rating": 5.0},
                {"user_id": 7, "movie_id": 44, "rating": 4.0},
                {"user_id": 7, "movie_id": 45, "rating": 2.0},
                {"user_id": 8, "movie_id": 41, "rating": 2.0},
                {"user_id": 8, "movie_id": 42, "rating": 4.5},
                {"user_id": 8, "movie_id": 43, "rating": 4.0},
                {"user_id": 8, "movie_id": 44, "rating": 3.5},
                {"user_id": 8, "movie_id": 45, "rating": 5.0},
                {"user_id": 9, "movie_id": 41, "rating": 4.0},
                {"user_id": 9, "movie_id": 42, "rating": 5.0},
                {"user_id": 9, "movie_id": 43, "rating": 2.5},
                {"user_id": 9, "movie_id": 44, "rating": 4.5},
                {"user_id": 9, "movie_id": 45, "rating": 3.0},
                {"user_id": 10, "movie_id": 41, "rating": 3.5},
                {"user_id": 10, "movie_id": 42, "rating": 4.0},
                {"user_id": 10, "movie_id": 43, "rating": 4.5},
                {"user_id": 10, "movie_id": 44, "rating": 2.0},
                {"user_id": 10, "movie_id": 45, "rating": 5.0},
                {"user_id": 11, "movie_id": 41, "rating": 4.5},
                {"user_id": 11, "movie_id": 42, "rating": 3.5},
                {"user_id": 11, "movie_id": 43, "rating": 4.0},
                {"user_id": 11, "movie_id": 44, "rating": 5.0},
                {"user_id": 11, "movie_id": 45, "rating": 2.5},
                {"user_id": 12, "movie_id": 41, "rating": 2.0},
                {"user_id": 12, "movie_id": 42, "rating": 4.0},
                {"user_id": 12, "movie_id": 43, "rating": 4.5},
                {"user_id": 12, "movie_id": 44, "rating": 3.0},
                {"user_id": 12, "movie_id": 45, "rating": 5.0},
                {"user_id": 13, "movie_id": 41, "rating": 4.0},
                {"user_id": 13, "movie_id": 42, "rating": 5.0},
                {"user_id": 13, "movie_id": 43, "rating": 3.5},
                {"user_id": 13, "movie_id": 44, "rating": 4.5},
                {"user_id": 13, "movie_id": 45, "rating": 2.0},
                {"user_id": 14, "movie_id": 41, "rating": 3.0},
                {"user_id": 14, "movie_id": 42, "rating": 4.5},
                {"user_id": 14, "movie_id": 43, "rating": 4.0},
                {"user_id": 14, "movie_id": 44, "rating": 2.5},
                {"user_id": 14, "movie_id": 45, "rating": 5.0},
                {"user_id": 15, "movie_id": 41, "rating": 4.5},
                {"user_id": 15, "movie_id": 42, "rating": 3.0},
                {"user_id": 15, "movie_id": 43, "rating": 5.0},
                {"user_id": 15, "movie_id": 44, "rating": 4.0},
                {"user_id": 15, "movie_id": 45, "rating": 2.5},
                # Películas 46-50
                {"user_id": 1, "movie_id": 46, "rating": 3.5},
                {"user_id": 1, "movie_id": 47, "rating": 4.0},
                {"user_id": 1, "movie_id": 48, "rating": 2.0},
                {"user_id": 1, "movie_id": 49, "rating": 4.5},
                {"user_id": 1, "movie_id": 50, "rating": 5.0},
                {"user_id": 2, "movie_id": 46, "rating": 4.0},
                {"user_id": 2, "movie_id": 47, "rating": 3.5},
                {"user_id": 2, "movie_id": 48, "rating": 4.5},
                {"user_id": 2, "movie_id": 49, "rating": 2.5},
                {"user_id": 2, "movie_id": 50, "rating": 3.0},
                {"user_id": 3, "movie_id": 46, "rating": 5.0},
                {"user_id": 3, "movie_id": 47, "rating": 4.0},
                {"user_id": 3, "movie_id": 48, "rating": 3.5},
                {"user_id": 3, "movie_id": 49, "rating": 4.5},
                {"user_id": 3, "movie_id": 50, "rating": 2.0},
                {"user_id": 4, "movie_id": 46, "rating": 2.5},
                {"user_id": 4, "movie_id": 47, "rating": 4.5},
                {"user_id": 4, "movie_id": 48, "rating": 4.0},
                {"user_id": 4, "movie_id": 49, "rating": 5.0},
                {"user_id": 4, "movie_id": 50, "rating": 3.5},
                {"user_id": 5, "movie_id": 46, "rating": 4.0},
                {"user_id": 5, "movie_id": 47, "rating": 5.0},
                {"user_id": 5, "movie_id": 48, "rating": 3.0},
                {"user_id": 5, "movie_id": 49, "rating": 2.5},
                {"user_id": 5, "movie_id": 50, "rating": 4.5},
                {"user_id": 6, "movie_id": 46, "rating": 3.5},
                {"user_id": 6, "movie_id": 47, "rating": 4.0},
                {"user_id": 6, "movie_id": 48, "rating": 5.0},
                {"user_id": 6, "movie_id": 49, "rating": 2.0},
                {"user_id": 6, "movie_id": 50, "rating": 4.5},
                {"user_id": 7, "movie_id": 46, "rating": 4.5},
                {"user_id": 7, "movie_id": 47, "rating": 3.0},
                {"user_id": 7, "movie_id": 48, "rating": 4.0},
                {"user_id": 7, "movie_id": 49, "rating": 5.0},
                {"user_id": 7, "movie_id": 50, "rating": 1.5},
                {"user_id": 8, "movie_id": 46, "rating": 2.0},
                {"user_id": 8, "movie_id": 47, "rating": 4.5},
                {"user_id": 8, "movie_id": 48, "rating": 4.0},
                {"user_id": 8, "movie_id": 49, "rating": 3.5},
                {"user_id": 8, "movie_id": 50, "rating": 5.0},
                {"user_id": 9, "movie_id": 46, "rating": 4.0},
                {"user_id": 9, "movie_id": 47, "rating": 5.0},
                {"user_id": 9, "movie_id": 48, "rating": 2.5},
                {"user_id": 9, "movie_id": 49, "rating": 4.5},
                {"user_id": 9, "movie_id": 50, "rating": 3.0},
                {"user_id": 10, "movie_id": 46, "rating": 3.5},
                {"user_id": 10, "movie_id": 47, "rating": 4.0},
                {"user_id": 10, "movie_id": 48, "rating": 4.5},
                {"user_id": 10, "movie_id": 49, "rating": 2.0},
                {"user_id": 10, "movie_id": 50, "rating": 5.0},
                {"user_id": 11, "movie_id": 46, "rating": 4.5},
                {"user_id": 11, "movie_id": 47, "rating": 3.5},
                {"user_id": 11, "movie_id": 48, "rating": 4.0},
                {"user_id": 11, "movie_id": 49, "rating": 5.0},
                {"user_id": 11, "movie_id": 50, "rating": 2.5},
                {"user_id": 12, "movie_id": 46, "rating": 2.0},
                {"user_id": 12, "movie_id": 47, "rating": 4.0},
                {"user_id": 12, "movie_id": 48, "rating": 4.5},
                {"user_id": 12, "movie_id": 49, "rating": 3.0},
                {"user_id": 12, "movie_id": 50, "rating": 5.0},
                {"user_id": 13, "movie_id": 46, "rating": 4.0},
                {"user_id": 13, "movie_id": 47, "rating": 5.0},
                {"user_id": 13, "movie_id": 48, "rating": 3.5},
                {"user_id": 13, "movie_id": 49, "rating": 4.5},
                {"user_id": 13, "movie_id": 50, "rating": 2.0},
                {"user_id": 14, "movie_id": 46, "rating": 3.0},
                {"user_id": 14, "movie_id": 47, "rating": 4.5},
                {"user_id": 14, "movie_id": 48, "rating": 4.0},
                {"user_id": 14, "movie_id": 49, "rating": 2.5},
                {"user_id": 14, "movie_id": 50, "rating": 5.0},
                {"user_id": 15, "movie_id": 46, "rating": 4.5},
                {"user_id": 15, "movie_id": 47, "rating": 3.0},
                {"user_id": 15, "movie_id": 48, "rating": 5.0},
                {"user_id": 15, "movie_id": 49, "rating": 4.0},
                {"user_id": 15, "movie_id": 50, "rating": 2.5},
            ]

            for rating_data in mock_ratings:
                # .add() no es asíncrono
                review = Review(**rating_data)
                session.add(review)

            # --- Commit de Ratings ---
            # NUEVO: 'await session.commit'
            await session.commit()
            print("Ratings mock agregados.")

            print("\nProceso de seeding completado.")
        except Exception as e:
            print(f"\n--- ERROR DURANTE EL SEEDING ---")
            print(f"Error: {e}")
            # NUEVO: 'await session.rollback'
            await session.rollback()
            print("Rollback realizado. La base de datos no ha sido modificada.")

    print("Proceso de seeding completado.")


async def create_db_and_tables():
    """
    Versión asíncrona que crea las tablas sin bloquear el event loop.
    """
    print("Creando tablas en la base de datos (async)...")

    # engine.run_sync() es la forma correcta de ejecutar
    # operaciones de SQLAlchemy síncronas (como create_all)
    # en un motor asíncrono.
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)

    print("Tablas creadas exitosamente.")






if __name__ == "__main__":
    create_db_and_tables()
