[project]
name = "discovery-recommendations"
version = "0.1.0"
description = "Modulo de busqueda y recomendaciones"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "fastapi[standard]>=0.116.1",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.11",
    "sqlmodel>=0.0.24",
    "strawberry-graphql[debug-server]>=0.281.0",
]
